version: '3.3'

services:
  drupal:
    image: drupal:latest
    ports: 
      - '8060:80'
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites

  postgres:
    image: postgres:9.6.2
    ports: 
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD:postgres
    volumes: 
      - postgres-db:/var/lib/postgresql/data

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  postgres-db: